-- MySQL Script generated by MySQL Workbench
-- Чт 25 авг 2022 12:21:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema common
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema common
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `common` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `common` ;

-- -----------------------------------------------------
-- Table `common`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(16) NULL,
  `age` INT NULL,
  `sex` CHAR NULL,
  `fname` VARCHAR(45) NULL,
  `about` TEXT(512) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `common`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `participants_max` INT NOT NULL,
  `about` TEXT(512) NULL,
  `coord` POINT NOT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `common`.`event_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common`.`event_participants` (
  `event_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `user_id`),
  INDEX `email_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_id_e_prtcpts`
    FOREIGN KEY (`event_id`)
    REFERENCES `common`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_id_e_prtcpts`
    FOREIGN KEY (`user_id`)
    REFERENCES `common`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `common`.`user_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common`.`user_images` (
  `u_image_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `URN` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`u_image_id`),
  UNIQUE INDEX `URN_UNIQUE` (`URN` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id_u_imgs`
    FOREIGN KEY (`user_id`)
    REFERENCES `common`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `common`.`event_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common`.`event_images` (
  `e_image_id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `URN` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`e_image_id`),
  UNIQUE INDEX `URN_UNIQUE` (`URN` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_id_e_imgs`
    FOREIGN KEY (`event_id`)
    REFERENCES `common`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `common`.`event_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common`.`event_messages` (
  `e_message_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `message` TEXT(512) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`e_message_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_id_e_msgs`
    FOREIGN KEY (`event_id`)
    REFERENCES `common`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_id_e_msgs`
    FOREIGN KEY (`user_id`)
    REFERENCES `common`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `common`.`private_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common`.`private_messages` (
  `p_message_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  `message` TEXT(512) NOT NULL,
  `date` DATETIME NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`p_message_id`),
  CONSTRAINT `fk_user_id_p_msgs`
    FOREIGN KEY (`user_id`)
    REFERENCES `common`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipient_id_p_msgs`
    FOREIGN KEY (`user_id`)
    REFERENCES `common`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
